DROP TABLE st4hdc.ADDRESS;

CREATE TABLE st4hdc.ADDRESS
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    ADDRESSTYPE varchar(1) NOT NULL,
    HOUSE_ID varchar(11),
    HOUSETYPE varchar(1) NOT NULL,
    ROOMNO varchar(10),
    CONDO varchar(75),
    HOUSENO varchar(75),
    SOISUB varchar(255),
    SOIMAIN varchar(255),
    ROAD varchar(255),
    VILLANAME varchar(255),
    VILLAGE varchar(2) NOT NULL,
    TAMBON varchar(2) NOT NULL,
    AMPUR varchar(2) NOT NULL,
    CHANGWAT varchar(2) NOT NULL,
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.ADDRESS ADD CONSTRAINT ADDRESS_PK PRIMARY KEY (HOSPCODE, PID, ADDRESSTYPE) ENABLED;

CREATE PROJECTION st4hdc.ADDRESS /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 ADDRESSTYPE,
 HOUSE_ID,
 HOUSETYPE,
 ROOMNO,
 CONDO,
 HOUSENO,
 SOISUB,
 SOIMAIN,
 ROAD,
 VILLANAME,
 VILLAGE,
 TAMBON,
 AMPUR,
 CHANGWAT,
 TELEPHONE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT ADDRESS.HOSPCODE,
        ADDRESS.PID,
        ADDRESS.ADDRESSTYPE,
        ADDRESS.HOUSE_ID,
        ADDRESS.HOUSETYPE,
        ADDRESS.ROOMNO,
        ADDRESS.CONDO,
        ADDRESS.HOUSENO,
        ADDRESS.SOISUB,
        ADDRESS.SOIMAIN,
        ADDRESS.ROAD,
        ADDRESS.VILLANAME,
        ADDRESS.VILLAGE,
        ADDRESS.TAMBON,
        ADDRESS.AMPUR,
        ADDRESS.CHANGWAT,
        ADDRESS.D_UPDATE,
        ADDRESS.CID,
        ADDRESS.HDC_DATE,
        ADDRESS.SOURCE_DATA
 FROM st4hdc.ADDRESS
 ORDER BY ADDRESS.HOSPCODE,
          ADDRESS.PID,
          ADDRESS.ADDRESSTYPE
SEGMENTED BY hash(ADDRESS.HOSPCODE, ADDRESS.PID, ADDRESS.ADDRESSTYPE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
