DROP TABLE st4hdc.CARE_REFER;

CREATE TABLE st4hdc.CARE_REFER
(
    HOSPCODE varchar(5) NOT NULL,
    REFERID varchar(10) NOT NULL,
    REFERID_PROVINCE varchar(10),
    CARETYPE varchar(1) NOT NULL,
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.CARE_REFER ADD CONSTRAINT CARE_REFER_PK PRIMARY KEY (HOSPCODE, REFERID, CARETYPE) ENABLED;

CREATE PROJECTION st4hdc.CARE_REFER /*+createtype(A)*/ 
(
 HOSPCODE,
 REFERID,
 REFERID_PROVINCE,
 CARETYPE,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT CARE_REFER.HOSPCODE,
        CARE_REFER.REFERID,
        CARE_REFER.REFERID_PROVINCE,
        CARE_REFER.CARETYPE,
        CARE_REFER.D_UPDATE,
        CARE_REFER.HDC_DATE,
        CARE_REFER.SOURCE_DATA
 FROM st4hdc.CARE_REFER
 ORDER BY CARE_REFER.HOSPCODE,
          CARE_REFER.REFERID,
          CARE_REFER.CARETYPE
SEGMENTED BY hash(CARE_REFER.HOSPCODE, CARE_REFER.REFERID, CARE_REFER.CARETYPE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
