DROP TABLE st4hdc.CHARGE_IPD;

CREATE TABLE st4hdc.CHARGE_IPD
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    AN varchar(9) NOT NULL,
    DATETIME_ADMIT timestamp NOT NULL,
    WARDSTAY varchar(5),
    CHARGEITEM varchar(2) NOT NULL,
    CHARGELIST varchar(6) NOT NULL,
    QUANTITY numeric(11,0),
    INSTYPE varchar(4) NOT NULL,
    COST numeric(11,2),
    PRICE numeric(11,2) NOT NULL,
    PAYPRICE numeric(11,2) NOT NULL,
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.CHARGE_IPD ADD CONSTRAINT CHARGE_IPD_PK PRIMARY KEY (HOSPCODE, PID, AN, DATETIME_ADMIT, CHARGEITEM, CHARGELIST, INSTYPE) ENABLED;

CREATE PROJECTION st4hdc.CHARGE_IPD /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 AN,
 DATETIME_ADMIT,
 WARDSTAY,
 CHARGEITEM,
 CHARGELIST,
 QUANTITY,
 INSTYPE,
 COST,
 PRICE,
 PAYPRICE,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT CHARGE_IPD.HOSPCODE,
        CHARGE_IPD.PID,
        CHARGE_IPD.AN,
        CHARGE_IPD.DATETIME_ADMIT,
        CHARGE_IPD.WARDSTAY,
        CHARGE_IPD.CHARGEITEM,
        CHARGE_IPD.CHARGELIST,
        CHARGE_IPD.QUANTITY,
        CHARGE_IPD.INSTYPE,
        CHARGE_IPD.COST,
        CHARGE_IPD.PRICE,
        CHARGE_IPD.PAYPRICE,
        CHARGE_IPD.D_UPDATE,
        CHARGE_IPD.CID,
        CHARGE_IPD.HDC_DATE,
        CHARGE_IPD.SOURCE_DATA
 FROM st4hdc.CHARGE_IPD
 ORDER BY CHARGE_IPD.HOSPCODE,
          CHARGE_IPD.PID,
          CHARGE_IPD.AN,
          CHARGE_IPD.DATETIME_ADMIT,
          CHARGE_IPD.CHARGEITEM,
          CHARGE_IPD.CHARGELIST,
          CHARGE_IPD.INSTYPE
SEGMENTED BY hash(CHARGE_IPD.HOSPCODE, CHARGE_IPD.PID, CHARGE_IPD.AN, CHARGE_IPD.DATETIME_ADMIT, CHARGE_IPD.CHARGEITEM, CHARGE_IPD.CHARGELIST, CHARGE_IPD.INSTYPE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
