DROP TABLE st4hdc.CHRONICFU;

CREATE TABLE st4hdc.CHRONICFU
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16),
    DATE_SERV date NOT NULL,
    WEIGHT numeric(5,1) NOT NULL,
    HEIGHT numeric(3,0) NOT NULL,
    WAIST_CM numeric(3,0) NOT NULL,
    SBP numeric(3,0) NOT NULL,
    DBP numeric(3,0) NOT NULL,
    FOOT char(1) NOT NULL,
    RETINA char(1) NOT NULL,
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.CHRONICFU ADD CONSTRAINT CHRONICFU_PK PRIMARY KEY (HOSPCODE, PID, SEQ, DATE_SERV, D_UPDATE) ENABLED;

CREATE PROJECTION st4hdc.CHRONICFU /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 WEIGHT,
 HEIGHT,
 WAIST_CM,
 SBP,
 DBP,
 FOOT,
 RETINA,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT CHRONICFU.HOSPCODE,
        CHRONICFU.PID,
        CHRONICFU.SEQ,
        CHRONICFU.DATE_SERV,
        CHRONICFU.WEIGHT,
        CHRONICFU.HEIGHT,
        CHRONICFU.WAIST_CM,
        CHRONICFU.SBP,
        CHRONICFU.DBP,
        CHRONICFU.FOOT,
        CHRONICFU.RETINA,
        CHRONICFU.PROVIDER,
        CHRONICFU.D_UPDATE,
        CHRONICFU.CID,
        CHRONICFU.HDC_DATE,
        CHRONICFU.SOURCE_DATA
 FROM st4hdc.CHRONICFU
 ORDER BY CHRONICFU.HOSPCODE,
          CHRONICFU.PID,
          CHRONICFU.SEQ,
          CHRONICFU.DATE_SERV,
          CHRONICFU.D_UPDATE
SEGMENTED BY hash(CHRONICFU.HOSPCODE, CHRONICFU.PID, CHRONICFU.SEQ, CHRONICFU.DATE_SERV, CHRONICFU.D_UPDATE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
