DROP TABLE st4hdc.COMMUNITY_SERVICE;

CREATE TABLE st4hdc.COMMUNITY_SERVICE
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16) NOT NULL,
    DATE_SERV date NOT NULL,
    COMSERVICE varchar(7) NOT NULL,
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.COMMUNITY_SERVICE ADD CONSTRAINT COMMUNITY_SERVICE_PK PRIMARY KEY (HOSPCODE, PID, SEQ, COMSERVICE) ENABLED;

CREATE PROJECTION st4hdc.COMMUNITY_SERVICE /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 COMSERVICE,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT COMMUNITY_SERVICE.HOSPCODE,
        COMMUNITY_SERVICE.PID,
        COMMUNITY_SERVICE.SEQ,
        COMMUNITY_SERVICE.DATE_SERV,
        COMMUNITY_SERVICE.COMSERVICE,
        COMMUNITY_SERVICE.PROVIDER,
        COMMUNITY_SERVICE.D_UPDATE,
        COMMUNITY_SERVICE.CID,
        COMMUNITY_SERVICE.HDC_DATE,
        COMMUNITY_SERVICE.SOURCE_DATA
 FROM st4hdc.COMMUNITY_SERVICE
 ORDER BY COMMUNITY_SERVICE.HOSPCODE,
          COMMUNITY_SERVICE.PID,
          COMMUNITY_SERVICE.SEQ,
          COMMUNITY_SERVICE.COMSERVICE
SEGMENTED BY hash(COMMUNITY_SERVICE.HOSPCODE, COMMUNITY_SERVICE.PID, COMMUNITY_SERVICE.SEQ, COMMUNITY_SERVICE.COMSERVICE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
