DROP TABLE st4hdc.COMMUNITY_ACTIVITY;

CREATE TABLE st4hdc.COMMUNITY_ACTIVITY
(
    HOSPCODE varchar(5) NOT NULL,
    VID varchar(8) NOT NULL,
    DATE_START date NOT NULL,
    DATE_FINISH date,
    COMACTIVITY varchar(7) NOT NULL,
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.COMMUNITY_ACTIVITY ADD CONSTRAINT COMMUNITY_ACTIVITY_PK PRIMARY KEY (HOSPCODE, VID, DATE_START, COMACTIVITY) ENABLED;

CREATE PROJECTION st4hdc.COMMUNITY_ACTIVITY /*+createtype(A)*/ 
(
 HOSPCODE,
 VID,
 DATE_START,
 DATE_FINISH,
 COMACTIVITY,
 PROVIDER,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT COMMUNITY_ACTIVITY.HOSPCODE,
        COMMUNITY_ACTIVITY.VID,
        COMMUNITY_ACTIVITY.DATE_START,
        COMMUNITY_ACTIVITY.DATE_FINISH,
        COMMUNITY_ACTIVITY.COMACTIVITY,
        COMMUNITY_ACTIVITY.PROVIDER,
        COMMUNITY_ACTIVITY.D_UPDATE,
        COMMUNITY_ACTIVITY.HDC_DATE,
        COMMUNITY_ACTIVITY.SOURCE_DATA
 FROM st4hdc.COMMUNITY_ACTIVITY
 ORDER BY COMMUNITY_ACTIVITY.HOSPCODE,
          COMMUNITY_ACTIVITY.VID,
          COMMUNITY_ACTIVITY.DATE_START,
          COMMUNITY_ACTIVITY.COMACTIVITY
SEGMENTED BY hash(COMMUNITY_ACTIVITY.HOSPCODE, COMMUNITY_ACTIVITY.VID, COMMUNITY_ACTIVITY.DATE_START, COMMUNITY_ACTIVITY.COMACTIVITY) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
