DROP TABLE st4hdc.DISABILITY;

CREATE TABLE st4hdc.DISABILITY
(
    HOSPCODE varchar(5) NOT NULL,
    DISABID varchar(13),
    PID varchar(15) NOT NULL,
    DISABTYPE char(1) NOT NULL,
    DISABCAUSE char(1),
    DIAGCODE varchar(6),
    DATE_DETECT date NOT NULL,
    DATE_DISAB date,
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.DISABILITY ADD CONSTRAINT DISABILITY_PK PRIMARY KEY (HOSPCODE, PID, DISABTYPE) ENABLED;

CREATE PROJECTION st4hdc.DISABILITY /*+createtype(A)*/ 
(
 HOSPCODE,
 DISABID,
 PID,
 DISABTYPE,
 DISABCAUSE,
 DIAGCODE,
 DATE_DETECT,
 DATE_DISAB,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT DISABILITY.HOSPCODE,
        DISABILITY.DISABID,
        DISABILITY.PID,
        DISABILITY.DISABTYPE,
        DISABILITY.DISABCAUSE,
        DISABILITY.DIAGCODE,
        DISABILITY.DATE_DETECT,
        DISABILITY.DATE_DISAB,
        DISABILITY.D_UPDATE,
        DISABILITY.CID,
        DISABILITY.HDC_DATE,
        DISABILITY.SOURCE_DATA
 FROM st4hdc.DISABILITY
 ORDER BY DISABILITY.HOSPCODE,
          DISABILITY.PID,
          DISABILITY.DISABTYPE
SEGMENTED BY hash(DISABILITY.HOSPCODE, DISABILITY.PID, DISABILITY.DISABTYPE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
