DROP TABLE st4hdc.DIAGNOSIS_OPD;

CREATE TABLE st4hdc.DIAGNOSIS_OPD
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16) NOT NULL,
    DATE_SERV date NOT NULL,
    DIAGTYPE varchar(1) NOT NULL,
    DIAGCODE varchar(6) NOT NULL,
    CLINIC varchar(5) NOT NULL,
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.DIAGNOSIS_OPD ADD CONSTRAINT DIAGNOSIS_OPD_PK PRIMARY KEY (HOSPCODE, PID, SEQ, DATE_SERV, DIAGCODE) ENABLED;

CREATE PROJECTION st4hdc.DIAGNOSIS_OPD /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 DIAGTYPE,
 DIAGCODE,
 CLINIC,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT DIAGNOSIS_OPD.HOSPCODE,
        DIAGNOSIS_OPD.PID,
        DIAGNOSIS_OPD.SEQ,
        DIAGNOSIS_OPD.DATE_SERV,
        DIAGNOSIS_OPD.DIAGTYPE,
        DIAGNOSIS_OPD.DIAGCODE,
        DIAGNOSIS_OPD.CLINIC,
        DIAGNOSIS_OPD.PROVIDER,
        DIAGNOSIS_OPD.D_UPDATE,
        DIAGNOSIS_OPD.CID,
        DIAGNOSIS_OPD.HDC_DATE,
        DIAGNOSIS_OPD.SOURCE_DATA
 FROM st4hdc.DIAGNOSIS_OPD
 ORDER BY DIAGNOSIS_OPD.HOSPCODE,
          DIAGNOSIS_OPD.PID,
          DIAGNOSIS_OPD.SEQ,
          DIAGNOSIS_OPD.DATE_SERV,
          DIAGNOSIS_OPD.DIAGCODE
SEGMENTED BY hash(DIAGNOSIS_OPD.HOSPCODE, DIAGNOSIS_OPD.PID, DIAGNOSIS_OPD.SEQ, DIAGNOSIS_OPD.DATE_SERV, DIAGNOSIS_OPD.DIAGCODE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
