DROP TABLE st4hdc.DRUG_OPD;

CREATE TABLE st4hdc.DRUG_OPD
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16) NOT NULL,
    DATE_SERV date NOT NULL,
    CLINIC varchar(5) NOT NULL,
    DIDSTD varchar(24) NOT NULL,
    DNAME varchar(255),
    AMOUNT numeric(12,0),
    UNIT varchar(3),
    UNIT_PACKING varchar(20),
    DRUGPRICE numeric(11,2),
    DRUGCOST numeric(11,2),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.DRUG_OPD ADD CONSTRAINT DRUG_OPD_PK PRIMARY KEY (HOSPCODE, PID, SEQ, DATE_SERV, DIDSTD) ENABLED;


CREATE PROJECTION st4hdc.DRUG_OPD /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 CLINIC,
 DIDSTD,
 DNAME,
 AMOUNT,
 UNIT,
 UNIT_PACKING,
 DRUGPRICE,
 DRUGCOST,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT DRUG_OPD.HOSPCODE,
        DRUG_OPD.PID,
        DRUG_OPD.SEQ,
        DRUG_OPD.DATE_SERV,
        DRUG_OPD.CLINIC,
        DRUG_OPD.DIDSTD,
        DRUG_OPD.DNAME,
        DRUG_OPD.AMOUNT,
        DRUG_OPD.UNIT,
        DRUG_OPD.UNIT_PACKING,
        DRUG_OPD.DRUGPRICE,
        DRUG_OPD.DRUGCOST,
        DRUG_OPD.PROVIDER,
        DRUG_OPD.D_UPDATE,
        DRUG_OPD.CID,
        DRUG_OPD.HDC_DATE,
        DRUG_OPD.SOURCE_DATA
 FROM st4hdc.DRUG_OPD
 ORDER BY DRUG_OPD.HOSPCODE,
          DRUG_OPD.PID,
          DRUG_OPD.SEQ,
          DRUG_OPD.DATE_SERV,
          DRUG_OPD.DIDSTD
SEGMENTED BY hash(DRUG_OPD.HOSPCODE, DRUG_OPD.PID, DRUG_OPD.SEQ, DRUG_OPD.DATE_SERV, DRUG_OPD.DIDSTD) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
