DROP TABLE st4hdc.DRUG_IPD;

CREATE TABLE st4hdc.DRUG_IPD
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    AN varchar(9) NOT NULL,
    DATETIME_ADMIT timestamp NOT NULL,
    WARDSTAY varchar(5) NOT NULL,
    TYPEDRUG char(1) NOT NULL,
    DIDSTD varchar(24) NOT NULL,
    DNAME varchar(255),
    DATESTART date,
    DATEFINISH date,
    AMOUNT numeric(12,0),
    UNIT varchar(3),
    UNIT_PACKING varchar(20),
    DRUGPRICE numeric(11,2),
    DRUGCOST numeric(11,2),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.DRUG_IPD ADD CONSTRAINT DRUG_IPD_PK PRIMARY KEY (HOSPCODE, PID, AN, TYPEDRUG, DIDSTD) ENABLED;

CREATE PROJECTION st4hdc.DRUG_IPD /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 AN,
 DATETIME_ADMIT,
 WARDSTAY,
 TYPEDRUG,
 DIDSTD,
 DNAME,
 DATESTART,
 DATEFINISH,
 AMOUNT,
 UNIT,
 UNIT_PACKING,
 DRUGPRICE,
 DRUGCOST,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT DRUG_IPD.HOSPCODE,
        DRUG_IPD.PID,
        DRUG_IPD.AN,
        DRUG_IPD.DATETIME_ADMIT,
        DRUG_IPD.WARDSTAY,
        DRUG_IPD.TYPEDRUG,
        DRUG_IPD.DIDSTD,
        DRUG_IPD.DNAME,
        DRUG_IPD.DATESTART,
        DRUG_IPD.DATEFINISH,
        DRUG_IPD.AMOUNT,
        DRUG_IPD.UNIT,
        DRUG_IPD.UNIT_PACKING,
        DRUG_IPD.DRUGPRICE,
        DRUG_IPD.DRUGCOST,
        DRUG_IPD.PROVIDER,
        DRUG_IPD.D_UPDATE,
        DRUG_IPD.CID,
        DRUG_IPD.HDC_DATE,
        DRUG_IPD.SOURCE_DATA
 FROM st4hdc.DRUG_IPD
 ORDER BY DRUG_IPD.HOSPCODE,
          DRUG_IPD.PID,
          DRUG_IPD.AN,
          DRUG_IPD.TYPEDRUG,
          DRUG_IPD.DIDSTD
SEGMENTED BY hash(DRUG_IPD.HOSPCODE, DRUG_IPD.PID, DRUG_IPD.AN, DRUG_IPD.TYPEDRUG, DRUG_IPD.DIDSTD) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);