DROP TABLE st4hdc.DRUG_REFER;

CREATE TABLE st4hdc.DRUG_REFER
(
    HOSPCODE varchar(5) NOT NULL,
    REFERID varchar(10) NOT NULL,
    REFERID_PROVINCE varchar(10),
    DATETIME_DSTART timestamp NOT NULL,
    DATETIME_DFINISH timestamp,
    DIDSTD varchar(24) NOT NULL,
    DNAME varchar(255),
    DDESCRIPTION varchar(255),
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.DRUG_REFER ADD CONSTRAINT DRUG_REFER_PK PRIMARY KEY (HOSPCODE, REFERID, DATETIME_DSTART, DIDSTD) ENABLED;

CREATE PROJECTION st4hdc.DRUG_REFER /*+createtype(A)*/ 
(
 HOSPCODE,
 REFERID,
 REFERID_PROVINCE,
 DATETIME_DSTART,
 DATETIME_DFINISH,
 DIDSTD,
 DNAME,
 DDESCRIPTION,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT DRUG_REFER.HOSPCODE,
        DRUG_REFER.REFERID,
        DRUG_REFER.REFERID_PROVINCE,
        DRUG_REFER.DATETIME_DSTART,
        DRUG_REFER.DATETIME_DFINISH,
        DRUG_REFER.DIDSTD,
        DRUG_REFER.DNAME,
        DRUG_REFER.DDESCRIPTION,
        DRUG_REFER.D_UPDATE,
        DRUG_REFER.HDC_DATE,
        DRUG_REFER.SOURCE_DATA
 FROM st4hdc.DRUG_REFER
 ORDER BY DRUG_REFER.HOSPCODE,
          DRUG_REFER.REFERID,
          DRUG_REFER.DATETIME_DSTART,
          DRUG_REFER.DIDSTD
SEGMENTED BY hash(DRUG_REFER.HOSPCODE, DRUG_REFER.REFERID, DRUG_REFER.DATETIME_DSTART, DRUG_REFER.DIDSTD) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
