DROP TABLE st4hdc.EPI;

CREATE TABLE st4hdc.EPI
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16),
    DATE_SERV date NOT NULL,
    VACCINETYPE varchar(3) NOT NULL,
    VACCINEPLACE varchar(5),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.EPI ADD CONSTRAINT EPI_PK PRIMARY KEY (HOSPCODE, PID, DATE_SERV, VACCINETYPE) ENABLED;

CREATE PROJECTION st4hdc.EPI /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 VACCINETYPE,
 VACCINEPLACE,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT EPI.HOSPCODE,
        EPI.PID,
        EPI.SEQ,
        EPI.DATE_SERV,
        EPI.VACCINETYPE,
        EPI.VACCINEPLACE,
        EPI.PROVIDER,
        EPI.D_UPDATE,
        EPI.CID,
        EPI.HDC_DATE,
        EPI.SOURCE_DATA
 FROM st4hdc.EPI
 ORDER BY EPI.HOSPCODE,
          EPI.PID,
          EPI.DATE_SERV,
          EPI.VACCINETYPE
SEGMENTED BY hash(EPI.HOSPCODE, EPI.PID, EPI.DATE_SERV, EPI.VACCINETYPE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
