DROP TABLE st4hdc.INVESTIGATION_REFER;

CREATE TABLE st4hdc.INVESTIGATION_REFER
(
    HOSPCODE varchar(5) NOT NULL,
    REFERID varchar(10) NOT NULL,
    REFERID_PROVINCE varchar(10),
    DATETIME_INVEST timestamp NOT NULL,
    INVESTCODE varchar(6) NOT NULL,
    INVESTNAME varchar(255),
    DATETIME_REPORT timestamp,
    INVESTVALUE numeric(6,2),
    INVESTRESULT varchar(255),
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.INVESTIGATION_REFER ADD CONSTRAINT INVESTIGATION_REFER_PK PRIMARY KEY (HOSPCODE, REFERID, DATETIME_INVEST, INVESTCODE) ENABLED;

CREATE PROJECTION st4hdc.INVESTIGATION_REFER /*+createtype(A)*/ 
(
 HOSPCODE,
 REFERID,
 REFERID_PROVINCE,
 DATETIME_INVEST,
 INVESTCODE,
 INVESTNAME,
 DATETIME_REPORT,
 INVESTVALUE,
 INVESTRESULT,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT INVESTIGATION_REFER.HOSPCODE,
        INVESTIGATION_REFER.REFERID,
        INVESTIGATION_REFER.REFERID_PROVINCE,
        INVESTIGATION_REFER.DATETIME_INVEST,
        INVESTIGATION_REFER.INVESTCODE,
        INVESTIGATION_REFER.INVESTNAME,
        INVESTIGATION_REFER.DATETIME_REPORT,
        INVESTIGATION_REFER.INVESTVALUE,
        INVESTIGATION_REFER.INVESTRESULT,
        INVESTIGATION_REFER.D_UPDATE,
        INVESTIGATION_REFER.HDC_DATE,
        INVESTIGATION_REFER.SOURCE_DATA
 FROM st4hdc.INVESTIGATION_REFER
 ORDER BY INVESTIGATION_REFER.HOSPCODE,
          INVESTIGATION_REFER.REFERID,
          INVESTIGATION_REFER.DATETIME_INVEST,
          INVESTIGATION_REFER.INVESTCODE
SEGMENTED BY hash(INVESTIGATION_REFER.HOSPCODE, INVESTIGATION_REFER.REFERID, INVESTIGATION_REFER.DATETIME_INVEST, INVESTIGATION_REFER.INVESTCODE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
