DROP TABLE st4hdc.NCDSCREEN;

CREATE TABLE st4hdc.NCDSCREEN
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16),
    DATE_SERV date NOT NULL,
    SERVPLACE varchar(1),
    SMOKE varchar(1),
    ALCOHOL varchar(1),
    DMFAMILY varchar(1),
    HTFAMILY varchar(1),
    WEIGHT numeric(5,1) NOT NULL,
    HEIGHT numeric(3,0) NOT NULL,
    WAIST_CM numeric(3,0) NOT NULL,
    SBP_1 numeric(3,0) NOT NULL,
    DBP_1 numeric(3,0) NOT NULL,
    SBP_2 numeric(3,0),
    DBP_2 numeric(3,0),
    BSLEVEL numeric(6,0),
    BSTEST char(1),
    SCREENPLACE varchar(5),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.NCDSCREEN ADD CONSTRAINT NCDSCREEN_PK PRIMARY KEY (HOSPCODE, PID, DATE_SERV) ENABLED;

CREATE PROJECTION st4hdc.NCDSCREEN /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 SERVPLACE,
 SMOKE,
 ALCOHOL,
 DMFAMILY,
 HTFAMILY,
 WEIGHT,
 HEIGHT,
 WAIST_CM,
 SBP_1,
 DBP_1,
 SBP_2,
 DBP_2,
 BSLEVEL,
 BSTEST,
 SCREENPLACE,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT NCDSCREEN.HOSPCODE,
        NCDSCREEN.PID,
        NCDSCREEN.SEQ,
        NCDSCREEN.DATE_SERV,
        NCDSCREEN.SERVPLACE,
        NCDSCREEN.SMOKE,
        NCDSCREEN.ALCOHOL,
        NCDSCREEN.DMFAMILY,
        NCDSCREEN.HTFAMILY,
        NCDSCREEN.WEIGHT,
        NCDSCREEN.HEIGHT,
        NCDSCREEN.WAIST_CM,
        NCDSCREEN.SBP_1,
        NCDSCREEN.DBP_1,
        NCDSCREEN.SBP_2,
        NCDSCREEN.DBP_2,
        NCDSCREEN.BSLEVEL,
        NCDSCREEN.BSTEST,
        NCDSCREEN.SCREENPLACE,
        NCDSCREEN.PROVIDER,
        NCDSCREEN.D_UPDATE,
        NCDSCREEN.CID,
        NCDSCREEN.HDC_DATE,
        NCDSCREEN.SOURCE_DATA
 FROM st4hdc.NCDSCREEN
 ORDER BY NCDSCREEN.HOSPCODE,
          NCDSCREEN.PID,
          NCDSCREEN.DATE_SERV
SEGMENTED BY hash(NCDSCREEN.HOSPCODE, NCDSCREEN.PID, NCDSCREEN.DATE_SERV) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
