DROP TABLE st4hdc.NEWBORN;

CREATE TABLE st4hdc.NEWBORN
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    MPID varchar(15),
    GRAVIDA varchar(2),
    GA varchar(2),
    BDATE date NOT NULL,
    BTIME varchar(6),
    BPLACE char(1),
    BHOSP varchar(5),
    BIRTHNO char(1) NOT NULL,
    BTYPE char(1),
    BDOCTOR char(1),
    BWEIGHT numeric(4,0),
    ASPHYXIA char(1) NOT NULL,
    VITK char(1) NOT NULL,
    TSH char(1) NOT NULL,
    TSHRESULT numeric(5,1),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.NEWBORN ADD CONSTRAINT NEWBORN_PK PRIMARY KEY (HOSPCODE, PID, BDATE) ENABLED;

CREATE PROJECTION st4hdc.NEWBORN /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 MPID,
 GRAVIDA,
 GA,
 BDATE,
 BTIME,
 BPLACE,
 BHOSP,
 BIRTHNO,
 BTYPE,
 BDOCTOR,
 BWEIGHT,
 ASPHYXIA,
 VITK,
 TSH,
 TSHRESULT,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT NEWBORN.HOSPCODE,
        NEWBORN.PID,
        NEWBORN.MPID,
        NEWBORN.GRAVIDA,
        NEWBORN.GA,
        NEWBORN.BDATE,
        NEWBORN.BTIME,
        NEWBORN.BPLACE,
        NEWBORN.BHOSP,
        NEWBORN.BIRTHNO,
        NEWBORN.BTYPE,
        NEWBORN.BDOCTOR,
        NEWBORN.BWEIGHT,
        NEWBORN.ASPHYXIA,
        NEWBORN.VITK,
        NEWBORN.TSH,
        NEWBORN.TSHRESULT,
        NEWBORN.D_UPDATE,
        NEWBORN.CID,
        NEWBORN.HDC_DATE,
        NEWBORN.SOURCE_DATA
 FROM st4hdc.NEWBORN
 ORDER BY NEWBORN.HOSPCODE,
          NEWBORN.PID,
          NEWBORN.BDATE
SEGMENTED BY hash(NEWBORN.HOSPCODE, NEWBORN.PID, NEWBORN.BDATE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
