DROP TABLE st4hdc.NEWBORNCARE;

CREATE TABLE st4hdc.NEWBORNCARE
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16),
    BDATE date  NOT NULL,
    BCARE date NOT NULL,
    BCPLACE varchar(5),
    BCARERESULT char(1),
    FOOD char(1) NOT NULL,
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.NEWBORNCARE ADD CONSTRAINT NEWBORNCARE_PK PRIMARY KEY (HOSPCODE, PID, BCARE) ENABLED;

CREATE PROJECTION st4hdc.NEWBORNCARE /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 BDATE,
 BCARE,
 BCPLACE,
 BCARERESULT,
 FOOD,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT NEWBORNCARE.HOSPCODE,
        NEWBORNCARE.PID,
        NEWBORNCARE.SEQ,
        NEWBORNCARE.BDATE,
        NEWBORNCARE.BCARE,
        NEWBORNCARE.BCPLACE,
        NEWBORNCARE.BCARERESULT,
        NEWBORNCARE.FOOD,
        NEWBORNCARE.PROVIDER,
        NEWBORNCARE.D_UPDATE,
        NEWBORNCARE.CID,
        NEWBORNCARE.HDC_DATE,
        NEWBORNCARE.SOURCE_DATA
 FROM st4hdc.NEWBORNCARE
 ORDER BY NEWBORNCARE.HOSPCODE,
          NEWBORNCARE.PID,
          NEWBORNCARE.BCARE
SEGMENTED BY hash(NEWBORNCARE.HOSPCODE, NEWBORNCARE.PID, NEWBORNCARE.BCARE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
