DROP TABLE st4hdc.NUTRITION;

CREATE TABLE st4hdc.NUTRITION
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16),
    DATE_SERV date NOT NULL,
    NUTRITIONPLACE varchar(5),
    WEIGHT numeric(5,1) NOT NULL,
    HEIGHT numeric(3,0) NOT NULL,
    HEADCIRCUM numeric(3,0),
    CHILDDEVELOP char(1),
    FOOD char(1),
    BOTTLE char(1),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.NUTRITION ADD CONSTRAINT NUTRITION_PK PRIMARY KEY (HOSPCODE, PID, DATE_SERV) ENABLED;

CREATE PROJECTION st4hdc.NUTRITION /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 NUTRITIONPLACE,
 WEIGHT,
 HEIGHT,
 HEADCIRCUM,
 CHILDDEVELOP,
 FOOD,
 BOTTLE,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT NUTRITION.HOSPCODE,
        NUTRITION.PID,
        NUTRITION.SEQ,
        NUTRITION.DATE_SERV,
        NUTRITION.NUTRITIONPLACE,
        NUTRITION.WEIGHT,
        NUTRITION.HEIGHT,
        NUTRITION.HEADCIRCUM,
        NUTRITION.CHILDDEVELOP,
        NUTRITION.FOOD,
        NUTRITION.BOTTLE,
        NUTRITION.PROVIDER,
        NUTRITION.D_UPDATE,
        NUTRITION.CID,
        NUTRITION.HDC_DATE,
        NUTRITION.SOURCE_DATA
 FROM st4hdc.NUTRITION
 ORDER BY NUTRITION.HOSPCODE,
          NUTRITION.PID,
          NUTRITION.DATE_SERV
SEGMENTED BY hash(NUTRITION.HOSPCODE, NUTRITION.PID, NUTRITION.DATE_SERV) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
