DROP TABLE st4hdc.PRENATAL;

CREATE TABLE st4hdc.PRENATAL
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    GRAVIDA varchar(2) NOT NULL,
    LMP date NOT NULL,
    EDC date,
    VDRL_RESULT char(1) NOT NULL,
    HB_RESULT char(1) NOT NULL,
    HIV_RESULT char(1) NOT NULL,
    DATE_HCT date,
    HCT_RESULT numeric(2,0),
    THALASSEMIA char(1) NOT NULL,
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.PRENATAL ADD CONSTRAINT PRENATAL_PK PRIMARY KEY (HOSPCODE, PID, GRAVIDA) ENABLED;

CREATE PROJECTION st4hdc.PRENATAL /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 GRAVIDA,
 LMP,
 EDC,
 VDRL_RESULT,
 HB_RESULT,
 HIV_RESULT,
 DATE_HCT,
 HCT_RESULT,
 THALASSEMIA,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT PRENATAL.HOSPCODE,
        PRENATAL.PID,
        PRENATAL.GRAVIDA,
        PRENATAL.LMP,
        PRENATAL.EDC,
        PRENATAL.VDRL_RESULT,
        PRENATAL.HB_RESULT,
        PRENATAL.HIV_RESULT,
        PRENATAL.DATE_HCT,
        PRENATAL.HCT_RESULT,
        PRENATAL.THALASSEMIA,
        PRENATAL.D_UPDATE,
        PRENATAL.CID,
        PRENATAL.HDC_DATE,
        PRENATAL.SOURCE_DATA
 FROM st4hdc.PRENATAL
 ORDER BY PRENATAL.HOSPCODE,
          PRENATAL.PID,
          PRENATAL.GRAVIDA
SEGMENTED BY hash(PRENATAL.HOSPCODE, PRENATAL.PID, PRENATAL.GRAVIDA) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
