DROP TABLE st4hdc.PROCEDURE_REFER;

CREATE TABLE st4hdc.PROCEDURE_REFER
(
    HOSPCODE varchar(5) NOT NULL,
    REFERID varchar(10) NOT NULL,
    REFERID_PROVINCE varchar(10),
    TIMESTART timestamp NOT NULL,
    TIMEFINISH timestamp,
    PROCEDURENAME varchar(255),
    PROCEDCODE varchar(7) NOT NULL,
    PDESCRIPTION varchar(255),
    PROCEDRESULT varchar(255),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.PROCEDURE_REFER ADD CONSTRAINT PROCEDURE_REFER_PK PRIMARY KEY (HOSPCODE, REFERID, TIMESTART, PROCEDCODE) ENABLED;

CREATE PROJECTION st4hdc.PROCEDURE_REFER /*+createtype(A)*/ 
(
 HOSPCODE,
 REFERID,
 REFERID_PROVINCE,
 TIMESTART,
 TIMEFINISH,
 PROCEDURENAME,
 PROCEDCODE,
 PDESCRIPTION,
 PROCEDRESULT,
 PROVIDER,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT PROCEDURE_REFER.HOSPCODE,
        PROCEDURE_REFER.REFERID,
        PROCEDURE_REFER.REFERID_PROVINCE,
        PROCEDURE_REFER.TIMESTART,
        PROCEDURE_REFER.TIMEFINISH,
        PROCEDURE_REFER.PROCEDURENAME,
        PROCEDURE_REFER.PROCEDCODE,
        PROCEDURE_REFER.PDESCRIPTION,
        PROCEDURE_REFER.PROCEDRESULT,
        PROCEDURE_REFER.PROVIDER,
        PROCEDURE_REFER.D_UPDATE,
        PROCEDURE_REFER.HDC_DATE,
        PROCEDURE_REFER.SOURCE_DATA
 FROM st4hdc.PROCEDURE_REFER
 ORDER BY PROCEDURE_REFER.HOSPCODE,
          PROCEDURE_REFER.REFERID,
          PROCEDURE_REFER.TIMESTART,
          PROCEDURE_REFER.PROCEDCODE
SEGMENTED BY hash(PROCEDURE_REFER.HOSPCODE, PROCEDURE_REFER.REFERID, PROCEDURE_REFER.TIMESTART, PROCEDURE_REFER.PROCEDCODE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
