DROP TABLE st4hdc.PROVIDER;

CREATE TABLE st4hdc.PROVIDER
(
    HOSPCODE varchar(5) NOT NULL,
    PROVIDER varchar(15) NOT NULL,
    REGISTERNO varchar(15),
    COUNCIL varchar(2),
    CID varchar(13) NOT NULL,
    PRENAME varchar(20),
    NAME varchar(50) NOT NULL,
    LNAME varchar(50) NOT NULL,
    SEX varchar(1) NOT NULL,
    BIRTH date NOT NULL,
    PROVIDERTYPE varchar(2) NOT NULL,
    STARTDATE date NOT NULL,
    OUTDATE date,
    MOVEFROM varchar(5),
    MOVETO varchar(5),
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.PROVIDER ADD CONSTRAINT PROVIDER_PK PRIMARY KEY (HOSPCODE, PROVIDER) ENABLED;

CREATE PROJECTION st4hdc.PROVIDER /*+createtype(A)*/ 
(
 HOSPCODE,
 PROVIDER,
 REGISTERNO,
 COUNCIL,
 CID,
 PRENAME,
 NAME,
 LNAME,
 SEX,
 BIRTH,
 PROVIDERTYPE,
 STARTDATE,
 OUTDATE,
 MOVEFROM,
 MOVETO,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT PROVIDER.HOSPCODE,
        PROVIDER.PROVIDER,
        PROVIDER.REGISTERNO,
        PROVIDER.COUNCIL,
        PROVIDER.CID,
        PROVIDER.PRENAME,
        PROVIDER.NAME,
        PROVIDER.LNAME,
        PROVIDER.SEX,
        PROVIDER.BIRTH,
        PROVIDER.PROVIDERTYPE,
        PROVIDER.STARTDATE,
        PROVIDER.OUTDATE,
        PROVIDER.MOVEFROM,
        PROVIDER.MOVETO,
        PROVIDER.D_UPDATE,
        PROVIDER.HDC_DATE,
        PROVIDER.SOURCE_DATA
 FROM st4hdc.PROVIDER
 ORDER BY PROVIDER.HOSPCODE,
          PROVIDER.PROVIDER
SEGMENTED BY hash(PROVIDER.HOSPCODE, PROVIDER.PROVIDER) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
