DROP TABLE st4hdc.PROCEDURE_OPD;

CREATE TABLE st4hdc.PROCEDURE_OPD
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16) NOT NULL,
    DATE_SERV date NOT NULL,
    CLINIC varchar(5) NOT NULL,
    PROCEDCODE varchar(7) NOT NULL,
    SERVICEPRICE numeric(11,2),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.PROCEDURE_OPD ADD CONSTRAINT PROCEDURE_OPD_PK PRIMARY KEY (HOSPCODE, PID, SEQ, DATE_SERV, PROCEDCODE) ENABLED;

CREATE PROJECTION st4hdc.PROCEDURE_OPD /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 CLINIC,
 PROCEDCODE,
 SERVICEPRICE,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT PROCEDURE_OPD.HOSPCODE,
        PROCEDURE_OPD.PID,
        PROCEDURE_OPD.SEQ,
        PROCEDURE_OPD.DATE_SERV,
        PROCEDURE_OPD.CLINIC,
        PROCEDURE_OPD.PROCEDCODE,
        PROCEDURE_OPD.SERVICEPRICE,
        PROCEDURE_OPD.PROVIDER,
        PROCEDURE_OPD.D_UPDATE,
        PROCEDURE_OPD.CID,
        PROCEDURE_OPD.HDC_DATE,
        PROCEDURE_OPD.SOURCE_DATA
 FROM st4hdc.PROCEDURE_OPD
 ORDER BY PROCEDURE_OPD.HOSPCODE,
          PROCEDURE_OPD.PID,
          PROCEDURE_OPD.SEQ,
          PROCEDURE_OPD.DATE_SERV,
          PROCEDURE_OPD.PROCEDCODE
SEGMENTED BY hash(PROCEDURE_OPD.HOSPCODE, PROCEDURE_OPD.PID, PROCEDURE_OPD.SEQ, PROCEDURE_OPD.DATE_SERV, PROCEDURE_OPD.PROCEDCODE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
