DROP TABLE st4hdc.REFER_HISTORY;

CREATE TABLE st4hdc.REFER_HISTORY
(
    HOSPCODE varchar(5) NOT NULL,
    REFERID varchar(10) NOT NULL,
    REFERID_PROVINCE varchar(10),
    PID varchar(15) NOT NULL,
    SEQ varchar(16) NOT NULL,
    AN varchar(9),
    REFERID_ORIGIN varchar(10),
    HOSPCODE_ORIGIN varchar(5),
    DATETIME_SERV timestamp NOT NULL,
    DATETIME_ADMIT timestamp,
    DATETIME_REFER timestamp NOT NULL,
    CLINIC_REFER varchar(5),
    HOSP_DESTINATION varchar(5) NOT NULL,
    CHIEFCOMP varchar(255),
    PHYSICALEXAM varchar(255),
    DIAGFIRST varchar(255),
    DIAGLAST varchar(255) NOT NULL,
    PSTATUS varchar(255) NOT NULL,
    PTYPE varchar(1) NOT NULL,
    EMERGENCY varchar(1) NOT NULL,
    PTYPEDIS varchar(2),
    CAUSEOUT varchar(1) NOT NULL,
    REQUEST varchar(255),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.REFER_HISTORY ADD CONSTRAINT REFER_HISTORY_PK PRIMARY KEY (HOSPCODE, REFERID) ENABLED;

CREATE PROJECTION st4hdc.REFER_HISTORY /*+createtype(A)*/ 
(
 HOSPCODE,
 REFERID,
 REFERID_PROVINCE,
 PID,
 SEQ,
 AN,
 REFERID_ORIGIN,
 HOSPCODE_ORIGIN,
 DATETIME_SERV,
 DATETIME_ADMIT,
 DATETIME_REFER,
 CLINIC_REFER,
 HOSP_DESTINATION,
 CHIEFCOMP,
 PHYSICALEXAM,
 DIAGFIRST,
 DIAGLAST,
 PSTATUS,
 PTYPE,
 EMERGENCY,
 PTYPEDIS,
 CAUSEOUT,
 REQUEST,
 PROVIDER,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT REFER_HISTORY.HOSPCODE,
        REFER_HISTORY.REFERID,
        REFER_HISTORY.REFERID_PROVINCE,
        REFER_HISTORY.PID,
        REFER_HISTORY.SEQ,
        REFER_HISTORY.AN,
        REFER_HISTORY.REFERID_ORIGIN,
        REFER_HISTORY.HOSPCODE_ORIGIN,
        REFER_HISTORY.DATETIME_SERV,
        REFER_HISTORY.DATETIME_ADMIT,
        REFER_HISTORY.DATETIME_REFER,
        REFER_HISTORY.CLINIC_REFER,
        REFER_HISTORY.HOSP_DESTINATION,
        REFER_HISTORY.CHIEFCOMP,
        REFER_HISTORY.PHYSICALEXAM,
        REFER_HISTORY.DIAGFIRST,
        REFER_HISTORY.DIAGLAST,
        REFER_HISTORY.PSTATUS,
        REFER_HISTORY.PTYPE,
        REFER_HISTORY.EMERGENCY,
        REFER_HISTORY.PTYPEDIS,
        REFER_HISTORY.CAUSEOUT,
        REFER_HISTORY.REQUEST,
        REFER_HISTORY.PROVIDER,
        REFER_HISTORY.D_UPDATE,
        REFER_HISTORY.HDC_DATE,
        REFER_HISTORY.SOURCE_DATA
 FROM st4hdc.REFER_HISTORY
 ORDER BY REFER_HISTORY.HOSPCODE,
          REFER_HISTORY.REFERID
SEGMENTED BY hash(REFER_HISTORY.HOSPCODE, REFER_HISTORY.REFERID) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
