DROP TABLE st4hdc.REHABILITATION;

CREATE TABLE st4hdc.REHABILITATION
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16),
    AN varchar(9),
    DATE_ADMIT timestamp,
    DATE_SERV date NOT NULL,
    DATE_START date,
    DATE_FINISH date,
    REHABCODE varchar(7) NOT NULL,
    AT_DEVICE varchar(10),
    AT_NO numeric(2,0),
    REHABPLACE varchar(5),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.REHABILITATION ADD CONSTRAINT REHABILITATION_PK PRIMARY KEY (HOSPCODE, PID, DATE_SERV, REHABCODE) ENABLED;

CREATE PROJECTION st4hdc.REHABILITATION /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 AN,
 DATE_ADMIT,
 DATE_SERV,
 DATE_START,
 DATE_FINISH,
 REHABCODE,
 AT_DEVICE,
 AT_NO,
 REHABPLACE,
 PROVIDER,
 D_UPDATE,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT REHABILITATION.HOSPCODE,
        REHABILITATION.PID,
        REHABILITATION.SEQ,
        REHABILITATION.AN,
        REHABILITATION.DATE_ADMIT,
        REHABILITATION.DATE_SERV,
        REHABILITATION.DATE_START,
        REHABILITATION.DATE_FINISH,
        REHABILITATION.REHABCODE,
        REHABILITATION.AT_DEVICE,
        REHABILITATION.AT_NO,
        REHABILITATION.REHABPLACE,
        REHABILITATION.PROVIDER,
        REHABILITATION.D_UPDATE,
        REHABILITATION.HDC_DATE,
        REHABILITATION.SOURCE_DATA
 FROM st4hdc.REHABILITATION
 ORDER BY REHABILITATION.HOSPCODE,
          REHABILITATION.PID,
          REHABILITATION.DATE_SERV,
          REHABILITATION.REHABCODE
SEGMENTED BY hash(REHABILITATION.HOSPCODE, REHABILITATION.PID, REHABILITATION.DATE_SERV, REHABILITATION.REHABCODE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);