DROP TABLE st4hdc.SPECIALPP;

CREATE TABLE st4hdc.SPECIALPP
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16),
    DATE_SERV date NOT NULL,
    SERVPLACE char(1) NOT NULL,
    PPSPECIAL varchar(6) NOT NULL,
    PPSPLACE varchar(5),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.SPECIALPP ADD CONSTRAINT SPECIALPP_PK PRIMARY KEY (HOSPCODE, PID, DATE_SERV, PPSPECIAL) ENABLED;

CREATE PROJECTION st4hdc.SPECIALPP /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 SERVPLACE,
 PPSPECIAL,
 PPSPLACE,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT SPECIALPP.HOSPCODE,
        SPECIALPP.PID,
        SPECIALPP.SEQ,
        SPECIALPP.DATE_SERV,
        SPECIALPP.SERVPLACE,
        SPECIALPP.PPSPECIAL,
        SPECIALPP.PPSPLACE,
        SPECIALPP.PROVIDER,
        SPECIALPP.D_UPDATE,
        SPECIALPP.CID,
        SPECIALPP.HDC_DATE,
        SPECIALPP.SOURCE_DATA
 FROM st4hdc.SPECIALPP
 ORDER BY SPECIALPP.HOSPCODE,
          SPECIALPP.PID,
          SPECIALPP.DATE_SERV,
          SPECIALPP.PPSPECIAL
SEGMENTED BY hash(SPECIALPP.HOSPCODE, SPECIALPP.PID, SPECIALPP.DATE_SERV, SPECIALPP.PPSPECIAL) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
