DROP TABLE st4hdc.SURVEILLANCE;

CREATE TABLE st4hdc.SURVEILLANCE
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    SEQ varchar(16) NOT NULL,
    DATE_SERV date NOT NULL,
    AN varchar(9),
    DATETIME_ADMIT timestamp,
    SYNDROME varchar(4),
    DIAGCODE varchar(6) NOT NULL,
    CODE506 varchar(2) NOT NULL,
    DIAGCODELAST varchar(6),
    CODE506LAST varchar(2),
    ILLDATE date NOT NULL,
    ILLHOUSE varchar(75),
    ILLVILLAGE varchar(2) NOT NULL,
    ILLTAMBON varchar(2) NOT NULL,
    ILLAMPUR varchar(2) NOT NULL,
    ILLCHANGWAT varchar(2) NOT NULL,
    LATITUDE numeric(10,6),
    LONGITUDE numeric(10,6),
    PTSTATUS char(1) NOT NULL,
    DATE_DEATH date,
    COMPLICATION varchar(3),
    ORGANISM varchar(4),
    PROVIDER varchar(15),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.SURVEILLANCE ADD CONSTRAINT SURVEILLANCE_PK PRIMARY KEY (HOSPCODE, PID, SEQ, DIAGCODE) ENABLED;

CREATE PROJECTION st4hdc.SURVEILLANCE /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 SEQ,
 DATE_SERV,
 AN,
 DATETIME_ADMIT,
 SYNDROME,
 DIAGCODE,
 CODE506,
 DIAGCODELAST,
 CODE506LAST,
 ILLDATE,
 ILLHOUSE,
 ILLVILLAGE,
 ILLTAMBON,
 ILLAMPUR,
 ILLCHANGWAT,
 LATITUDE,
 LONGITUDE,
 PTSTATUS,
 DATE_DEATH,
 COMPLICATION,
 ORGANISM,
 PROVIDER,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT SURVEILLANCE.HOSPCODE,
        SURVEILLANCE.PID,
        SURVEILLANCE.SEQ,
        SURVEILLANCE.DATE_SERV,
        SURVEILLANCE.AN,
        SURVEILLANCE.DATETIME_ADMIT,
        SURVEILLANCE.SYNDROME,
        SURVEILLANCE.DIAGCODE,
        SURVEILLANCE.CODE506,
        SURVEILLANCE.DIAGCODELAST,
        SURVEILLANCE.CODE506LAST,
        SURVEILLANCE.ILLDATE,
        SURVEILLANCE.ILLHOUSE,
        SURVEILLANCE.ILLVILLAGE,
        SURVEILLANCE.ILLTAMBON,
        SURVEILLANCE.ILLAMPUR,
        SURVEILLANCE.ILLCHANGWAT,
        SURVEILLANCE.LATITUDE,
        SURVEILLANCE.LONGITUDE,
        SURVEILLANCE.PTSTATUS,
        SURVEILLANCE.DATE_DEATH,
        SURVEILLANCE.COMPLICATION,
        SURVEILLANCE.ORGANISM,
        SURVEILLANCE.PROVIDER,
        SURVEILLANCE.D_UPDATE,
        SURVEILLANCE.CID,
        SURVEILLANCE.HDC_DATE,
        SURVEILLANCE.SOURCE_DATA
 FROM st4hdc.SURVEILLANCE
 ORDER BY SURVEILLANCE.HOSPCODE,
          SURVEILLANCE.PID,
          SURVEILLANCE.SEQ,
          SURVEILLANCE.DIAGCODE
SEGMENTED BY hash(SURVEILLANCE.HOSPCODE, SURVEILLANCE.PID, SURVEILLANCE.SEQ, SURVEILLANCE.DIAGCODE) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
