DROP TABLE st4hdc.WOMEN;

CREATE TABLE st4hdc.WOMEN
(
    HOSPCODE varchar(5) NOT NULL,
    PID varchar(15) NOT NULL,
    FPTYPE varchar(1) NOT NULL,
    NOFPCAUSE char(1),
    TOTALSON numeric(2,0),
    NUMBERSON numeric(2,0),
    ABORTION numeric(2,0),
    STILLBIRTH numeric(2,0),
    D_UPDATE timestamp NOT NULL,
    CID varchar(13),
    HDC_DATE timestamp,
    SOURCE_DATA varchar(6)
);

ALTER TABLE st4hdc.WOMEN ADD CONSTRAINT WOMEN_PK PRIMARY KEY (HOSPCODE, PID) ENABLED;

CREATE PROJECTION st4hdc.WOMEN /*+createtype(A)*/ 
(
 HOSPCODE,
 PID,
 FPTYPE,
 NOFPCAUSE,
 TOTALSON,
 NUMBERSON,
 ABORTION,
 STILLBIRTH,
 D_UPDATE,
 CID,
 HDC_DATE,
 SOURCE_DATA
)
AS
 SELECT WOMEN.HOSPCODE,
        WOMEN.PID,
        WOMEN.FPTYPE,
        WOMEN.NOFPCAUSE,
        WOMEN.TOTALSON,
        WOMEN.NUMBERSON,
        WOMEN.ABORTION,
        WOMEN.STILLBIRTH,
        WOMEN.D_UPDATE,
        WOMEN.CID,
        WOMEN.HDC_DATE,
        WOMEN.SOURCE_DATA
 FROM st4hdc.WOMEN
 ORDER BY WOMEN.HOSPCODE,
          WOMEN.PID
SEGMENTED BY hash(WOMEN.HOSPCODE, WOMEN.PID) ALL NODES KSAFE 1;

--SELECT MARK_DESIGN_KSAFE(1);
